---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration
  - name: Execute custom pre-tasks
    include_tasks: "{{input_dir}}/{{ekara_configuration_params.params.pre_tasks}}"
    when: ekara_configuration_params.params.pre_tasks is defined
  tasks:
  - set_fact:
      ekara_keypair_name: "{{ekara_configuration_params.environment.name}}_{{ekara_configuration_params.environment.qualifier}}"
      ekara_temp_dir: "tmp-{{lookup('pipe','date') | to_uuid}}"
      ekara_stack_name: "{{ekara_configuration_params.environment.name}}"
      ekara_stack_id: "{{ekara_configuration_params.environment.id}}"
      ekara_plf: "{{ekara_configuration_params.environment.name}}_{{ekara_configuration_params.environment.qualifier}}"

  - name: Create Infrastructure
    block:
    - name: Create temp dir
      file:
        path: "{{ekara_temp_dir}}"
        state: directory
    - name: Create a new Openstack key pair
      os_keypair:
        name: "{{ekara_keypair_name}}"
        public_key: "{{ lookup('file', ekara_configuration_params.connectionConfig.machine_public_key) }}"

    - name: Provision a set of instances
      include_tasks: tasks/instances.yml

    - name: Provision volumes
      include_tasks: tasks/volumes.yml
      when:
      - ekara_configuration_params.volumes is defined
      - ekara_configuration_params.volumes|length > 0

    - name: Push outputs to engine
      template:
        src: "templates/output/{{item}}"
        dest: "{{output_dir}}/{{item}}"
      with_items:
      - params.yaml
      when:
      - ekara_configuration_params.volumes is defined
      - ekara_configuration_params.volumes|length > 0

    always:
    - name: Purge temp dir
      file:
        path: "{{ekara_temp_dir}}"
        state: absent

- name: Create Inventory
  import_playbook: inventory.yml
