---
- src: https://github.com/lagoon-platform/ansible-role-configuration.git
  version: alpha1
  name: lagoon.configuration

- src: https://github.com/lagoon-platform/ansible-role-ssh-config.git
  version: alpha2
  name: lagoon.ssh
