---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Checkout roles
    command: ansible-galaxy install -r requirements.yml

- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration
  tasks:
  - name: Check parameters
    block:
    - set_fact:
        required_vars:
        - input_dir
        - output_dir
        - ekara_configuration_params
    - name: Check required parameters
      fail: msg="Parameter '{{item}}' is not defined"
      when: item not in vars
      with_items: "{{required_vars}}"
    - name: Check required parameters in Params
      fail: msg="Parameter '{{item}}' is not defined in [ConnectionConfig] tag."
      when: item not in ekara_configuration_params.connectionConfig
      with_items:
      - provider
      - machine_private_key
      - machine_public_key

  - block:
    - name: Install Certificates
      become: true
      get_url:
        url: "{{item}}"
        dest: "/usr/local/share/ca-certificates/{{item|basename}}"
        mode: 0640
      with_items:
      - "{{ekara_configuration_params.params.cacert}}"
    - name: Update Certificates
      become: true
      shell:
        /usr/sbin/update-ca-certificates
    - name: Update certificates
      set_fact:
        ekara_os_cert:
          cacert: /etc/ssl/certs/ca-certificates.crt
    - name: Update config
      set_fact:
        ekara_config_cert: "{{ekara_configuration_params.params.config | combine(ekara_os_cert, recursive=True)}}"
    when:
    - ekara_configuration_params.params.cacert is defined

  # Bug in openstack python
  - set_fact:
      ekara_config_os: {}
  - set_fact:
      ekara_config_os: "{{ekara_config_os |combine({item.key: item.value})}}"
    when:
    - item.key not in ['identity_api_version']
    with_dict: "{{ekara_config_cert}}"
    loop_control:
      label: "{{item.key}}"

  - include_role:
      name: os-config

  - block:
    - name: Prepare Openstack installation
      become: true
      apk:
        name: python2-dev,gcc,libc-dev,linux-headers
        state: present
    - name: Install Openstack modules
      become: true
      pip:
        name:
        - openstacksdk==0.20.0
        - shade
        state: present
    - name: Remove temporary modules
      become: true
      apk:
        name: python2-dev,gcc,libc-dev,linux-headers
        state: absent

  - name: Return params for Openstack
    template:
      src: "templates/output/{{item}}"
      dest: "{{output_dir}}/{{item}}"
    with_items:
    - inventory.yaml
