heat_template_version: 2016-04-08

description: >
  Node template to create a full stack.

parameters:
  node_count:
    type: number
    description: Number of servers to create
  names:
    type: comma_delimited_list
    description: Name of nodes
  key:
    type: string
    description: Name of keypair to assign to server
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    description: Flavor to use for server
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach instance to.
  dns_zone:
    type: string
    description: DNS zone for server
  volumes:
    type: json
    description: Volumes for server
  volumes_count:
    type: number
    description: Number of volumes

resources:
  servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: node_count }
      resource_def:
        type: heat-server.yaml
        properties:
          stack_name: { get_param: "OS::stack_name" }
          key: { get_param: key }
          image: { get_param: image }
          flavor: { get_param: flavor }
          private_network: { get_param: private_network }
          public_network: { get_param: public_network }
          names: { get_param: names }
          index: '%index%'
          dns_zone: { get_param: dns_zone }
          volumes: { get_param: volumes }
          volumes_count: { get_param: volumes_count }

outputs:
  server_ids:
    value: {get_attr: [servers, server_id]}
  server_names:
    value: {get_attr: [servers, server_name]}
  volumes_ids:
    value: {get_attr: [servers, volumes_id]}
  volumes_names:
    value: {get_attr: [servers, volumes_name]}
